os: Visual Studio 2015

platform: Any CPU
configuration: Release

version: 1.0.{build}

#branches:
#  only:
#  - develop

#install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  - ps: Vsix-UpdateBuildVersion

#  - ps: Vsix-IncrementVsixVersion -versionType revision | Vsix-UpdateBuildVersion
#  - ps: Vsix-TokenReplacement src\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

before_build:
  - nuget restore -verbosity quiet

build:
  verbosity: minimal

build_script:
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

nuget:
  account_feed: true
  project_feed: false

after_build:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
